In [10]:
# 1 Array Creation and Basic Operations:
import numpy as np
array=np.arange(1,21)
add=array+5
sub=array-5
multi=array*5
div=array/5
print('addition:',add)
print('subtraction:',sub)
print('multiplication:',multi)
print('division:',div)

sum=array.sum()
mean=array.mean()
maxi=array.max()
mini=array.min()
print('sum:',sum)
print('mean:',mean)
print('max:',maxi)
print('min:',mini)

addition: [ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
subtraction: [-4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
multiplication: [  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]
division: [0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6
 3.8 4. ]
sum: 210
mean: 10.5
max: 20
min: 1


In [ ]:
# 2 
import numpy as np
arr2d=np.random.randint(10,50,(4,5))
print(arr2d)
column3=arr2d[:,2]
print('3rd column:',column3)
rows=arr2d[:2,:]
print('first two rows:',rows)

[[18 25 35 28 18]
 [48 11 26 17 47]
 [19 49 43 45 37]
 [37 43 32 36 41]]
3rd column: [35 26 43 32]
first two rows: [[18 25 35 28 18]
 [48 11 26 17 47]]


In [15]:
# 3 
array=np.random.randint(1,12,(3,4))
print(array)
array2=array.reshape(2,6)
print('reshaped array:',array2)
array3=array.reshape(6,2)
print(array3)

[[10  8  1  4]
 [ 5  6  2 11]
 [ 6  6  2 11]]
reshaped array: [[10  8  1  4  5  6]
 [ 2 11  6  6  2 11]]
[[10  8]
 [ 1  4]
 [ 5  6]
 [ 2 11]
 [ 6  6]
 [ 2 11]]


In [4]:
# 4 
import numpy as np
arr1=np.array([[1],[2],[3]])
arr2=np.array([[1,2,3,4]])
result=arr1+arr2
result

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [6]:
# 5 
array=np.random.rand(3,3)
array
mean=np.mean(array)
std=np.std(array)
var=np.var(array)
print('mean:',mean)
print('standard deviation:',std)
print('variance:',var)
median0=np.median(array,axis=0)
median1=np.median(array,axis=1)
print('median along axis 0:',median0)
print('median along axis 1:',median1)

mean: 0.6131236526436696
standard deviation: 0.24217623790687956
variance: 0.05864933020672953
median along axis 0: [0.72461704 0.72043505 0.45001167]
median along axis 1: [0.72461704 0.87495339 0.34173028]


In [10]:
# 6 
array=np.random.randint(50,100,15)
print(array)
sorted=np.sort(array)
print('sorted:',sorted)
indices=np.where(array>75)
print('indices greater than 75:',indices)

[91 90 94 54 69 96 55 60 65 84 82 91 77 59 72]
sorted: [54 55 59 60 65 69 72 77 82 84 90 91 91 94 96]
indices greater than 75: (array([ 0,  1,  2,  5,  9, 10, 11, 12]),)


In [17]:
# 7
arr1 = np.random.randint(1, 10, (3, 3))
arr2 = np.random.randint(1, 10, (3, 3))
add=arr1+arr2
sub=arr1-arr2
mult=arr1*arr2
div=arr1/arr2
dot_product=np.dot(arr1,arr2)
print(arr1)
print(arr2)
print('addition:',add)
print('subtraction:',sub)
print('multiplication:',mult)
print('division:',div)
print('dot product:',dot_product)

[[6 1 6]
 [5 5 6]
 [5 3 9]]
[[1 3 1]
 [7 6 9]
 [2 6 3]]
addition: [[ 7  4  7]
 [12 11 15]
 [ 7  9 12]]
subtraction: [[ 5 -2  5]
 [-2 -1 -3]
 [ 3 -3  6]]
multiplication: [[ 6  3  6]
 [35 30 54]
 [10 18 27]]
division: [[6.         0.33333333 6.        ]
 [0.71428571 0.83333333 0.66666667]
 [2.5        0.5        3.        ]]
dot product: [[25 60 33]
 [52 81 68]
 [44 87 59]]
