In [10]:
import numpy as np
array1d=np.array([1,2,3])
array1d.shape

(3,)

In [14]:
type(array1d)

numpy.ndarray

In [12]:

array1d.size

3

In [13]:
array1d.dtype

dtype('int64')

In [9]:
import numpy as np
array2d=np.array([[1,2,3],
                  [2,3,4]])
array2d.shape

(2, 3)

In [11]:
import numpy as np
array2d=np.array([[1,2,3],
                  [2,3,4]])
array2d.size

6

In [16]:
import numpy as np
array2d=np.array([[1,2,3],
                  [2,3,4]] ,dtype='float')
array2d

array([[1., 2., 3.],
       [2., 3., 4.]])

In [17]:
np.array((1,2,3))

array([1, 2, 3])

In [19]:
zero=np.zeros((3,4))
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
full=np.full((3,4),6 ,dtype='complex')
print(full)

[[6.+0.j 6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j 6.+0.j]]


In [25]:
e=np.random.random((2,3))
e

array([[0.31683916, 0.39668986, 0.61898313],
       [0.03911516, 0.16754311, 0.48622213]])

In [27]:
a=np.arange(0,40,5)
a

array([ 0,  5, 10, 15, 20, 25, 30, 35])

In [28]:
g=np.linspace(2,15,3)
g

array([ 2. ,  8.5, 15. ])

In [37]:

arra=np.array([[1,2,3,5],
             [2,3,4,5],
             [5,6,7,5]])
shapearr=arra.reshape(4,3)

print(shapearr)

[[1 2 3]
 [5 2 3]
 [4 5 5]
 [6 7 5]]


In [34]:
shapearr=arra.reshape(6,2)
print(shapearr)

[[1 2]
 [3 5]
 [2 3]
 [4 5]
 [5 6]
 [7 5]]


In [39]:
shapearr=arra.reshape(2,2,3)
print(shapearr)

[[[1 2 3]
  [5 2 3]]

 [[4 5 5]
  [6 7 5]]]


In [42]:
shapearr1=arra.flatten()
shapearr1

array([1, 2, 3, 5, 2, 3, 4, 5, 5, 6, 7, 5])